// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace CRM.Models
{
    public partial class Category
    {
        public Category()
        {
            Item = new HashSet<Item>();
        }

        [Key]
        public int CategoryId { get; set; }
        public string CategoryPic { get; set; }
        [Required]
        public bool IsActive { get; set; }
        [Column("DescriptionTLEN")]
        [Required(ErrorMessage = "Please enter The Description in English")]

        public string DescriptionTlen { get; set; }
        [Column("CategoryTLAR")]
        [Required(ErrorMessage = "Please enter The Category Name in Arabic")]

        public string CategoryTlar { get; set; }
        [Column("CategoryTLEN")]
        [Required(ErrorMessage = "Please enter The Category Name in English")]
        public string CategoryTlen { get; set; }
        [Column("DescriptionTLAR")]
        [Required(ErrorMessage = "Please enter The Description in Arabic")]
        public string DescriptionTlar { get; set; }
        [Required(ErrorMessage ="Please enter The Order Sort")]
        public int? SortOrder { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<Item> Item { get; set; }
    }
}