// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace CRM.Models
{
    public partial class Country
    {
        [Key]
        public int CountryId { get; set; }
        //[Required]
        //[Column("CountryTlen")]
        //public string CountryTlen { get; set; }
       
        [Column("CountryTLEN")]
        public string? CountryTlen { get; set; }
        public string? CountryTlar { get; set; }
        public string? Pic { get; set; }
        public bool? IsActive { get; set; }
        
        [Range(1, int.MaxValue, ErrorMessage = "Zero is not allowed")]
        public int? OrderIndex { get; set; }
        public int? CurrencyId { get; set; }
        public double? ShippingCost { get; set; }
        public double? tax { get; set; }

        [ForeignKey("CurrencyId")]
        [InverseProperty("Country")]
        [JsonIgnore]
        public virtual Currency? Currency { get; set; }

        
        [JsonIgnore]
        public ICollection<ItemPriceN> itemPriceNs { get; set; }= new HashSet<ItemPriceN>();   
        public ICollection<ShippingMatrix> ShippingsMatrix { get; set; }
    }
}