// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace CRM.Models
{
    public partial class Coupon
    {
        [Key]
        public int CouponId { get; set; }
        [Required]
        public string Serial { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ExpirationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime IssueDate { get; set; }
        public double? Amount { get; set; }
        public int CouponTypeId { get; set; }
        public bool Used { get; set; }
        [JsonIgnore]
        public virtual CouponType CouponType { get; set; }
    }
}