// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace CRM.Models
{
    public partial class Currency
    {
        public Currency()
        {
            Country = new HashSet<Country>();
        }

        [Key]
        public int CurrencyId { get; set; }
        [Required]
        [Column("CurrencyTLAR")]
        public string CurrencyTlar { get; set; }
        [Required]
        [Column("CurrencyTLEN")]
        public string CurrencyTlen { get; set; }
        public string CurrencyPic { get; set; }
        public bool IsActive { get; set; }

        [InverseProperty("Currency")]
        [JsonIgnore]
        public virtual ICollection<Country> Country { get; set; }
    }
}