// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace CRM.Models
{
    public partial class ItemPrice
    {
        [Key]
       // public int ItemsPriceId { get; set; }
        public int ItemPriceId { get; set; }
        public int ItemId { get; set; }
        //public int? CountryId { get; set; }
        public double? Price { get; set; }

        //[ForeignKey("ItemId")]
        //[InverseProperty("ItemPrice")]
        //[JsonIgnore]
        //public virtual Item Item { get; set; }

        //public virtual Country Country { get; set; }


    }
}