// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRM.Models
{
    public partial class ItemImage
    {
        [Key]
        public int ItemImageId { get; set; }
        public string ImageName { get; set; }
        public int ItemId { get; set; }

        [ForeignKey("ItemId")]
        [InverseProperty("ItemImageNavigation")]
        public virtual Item Item { get; set; }
    }
}