// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace CRM.Models
{
    public partial class Order
    {
       
        [Key]
        public int OrderId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime OrderDate { get; set; }
        public string OrderSerial { get; set; }
        public int? CustomerId { get; set; }
        public int? OrderStatusId { get; set; }
        public bool IsCanceled { get; set; } = false;
        public bool IsDeliverd { get; set; } = false;
        public string Notes { get; set; }
        public int? PaymentMethodId { get; set; }
        public string Tabbyres { get; set; }
        public int? CustomerAddressId { get; set; }
        public double? tax { get; set; }
        public int? CountryId { get; set; }
        public double OrderTotal { get; set; }
        public double? DiscountAmount { get; set; } = 0;
        public double OrderDiscount { get; set; }
        public double TotalWeight { get; set; }
        public int? CouponId { get; set; }
        public int? CouponTypeId { get; set; }
        public double? CouponAmount { get; set; }
        public double? Deliverycost { get; set; }
        public double? OrderNet { get; set; }
        public double? TotalAfterDiscount { get; set; }
        public string? ShippingLabel { get; set; }
        public string? ShippingNo{ get; set; }
        public bool IsPaid { get; set; }
        public string TabbyPaymentId { get; set; }
        public int? UniqeId { get; set; }
        [Column("PaymentID")]
        public string? PaymentId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PostDate { get; set; }
        [JsonIgnore]
        public virtual Coupon Coupon { get; set; }
        [JsonIgnore]
        public virtual CouponType CouponType { get; set; }
        [JsonIgnore]
        public virtual CustomerN CustomerN { get; set; }
        [JsonIgnore]
        public virtual Country Country { get; set; }
        [JsonIgnore]
        public virtual OrderStatus OrderStatus { get; set; }
        [JsonIgnore]
        public virtual CustomerAddress CustomerAddress { get; set; }
        [JsonIgnore]
        public virtual ICollection<OrderItem> OrderItem { get; set; }

        [JsonIgnore]
        public virtual ICollection<OrderTraking> OrderTrakings { get; set; }

    }
}